env: local

http_server:
  address: "0.0.0.0:8080"
  timeout: 5s
  idle_timeout: 60s

kafka:
  brokers:
    - "kafka:9092"
  input_topic: "messages_to_process"
  output_topic: "processed_messages"
  dead_letter_topic: "messages_failed"
  producer:
    acks: "all"
    timeout: 3s

retries:
  max_llm_attempts: 5

postgresql:
  host: "postgres"
  port: 5432
  user: "postgres"
  password: "postgres"
  dbname: "emails"
  sslmode: "disable"

org:
  file_path: "./configs/hierarchy.json"
